import type { PuzzlePack } from '../../../types/index.ts';

export const enGreetings: PuzzlePack = {
  id: 'en-greetings',
  titleKey: 'packs.greetings',
  icon: '\u{1F44B}',
  puzzles: [
    {
      id: 'en-greetings-good-morning',
      lang: 'en',
      pack: 'en-greetings',
      title: 'Good Morning',
      difficulty: 'easy',
      answer: 'GOOD MORNING',
      wordLengths: [4, 7],
      startPhrase: 'alarm clock rings',
      chain: [
        { left: 'alarm clock rings', syllable: 'GO', right: 'stretch and yawn', emojiLeft: '\u{23F0}', emojiRight: '\u{1F971}' },
        { left: 'stretch and yawn', syllable: 'OD', right: 'brush your teeth', emojiLeft: '\u{1F971}', emojiRight: '\u{1FAA5}' },
        { left: 'brush your teeth', syllable: 'MOR', right: 'eat breakfast', emojiLeft: '\u{1FAA5}', emojiRight: '\u{1F95E}' },
        { left: 'eat breakfast', syllable: 'NING', right: 'open the curtains', emojiLeft: '\u{1F95E}', emojiRight: '\u{1FA9F}' },
        { left: 'open the curtains', syllable: '', right: 'alarm clock rings', emojiLeft: '\u{1FA9F}', emojiRight: '\u{23F0}' },
      ],
    },
    {
      id: 'en-greetings-sweet-dreams',
      lang: 'en',
      pack: 'en-greetings',
      title: 'Sweet Dreams',
      difficulty: 'easy',
      answer: 'SWEET DREAMS',
      wordLengths: [5, 6],
      startPhrase: 'bedtime story',
      chain: [
        { left: 'bedtime story', syllable: 'SWE', right: 'cozy blanket', emojiLeft: '📖', emojiRight: '🛏️' },
        { left: 'cozy blanket', syllable: 'ET', right: 'close your eyes', emojiLeft: '🛏️', emojiRight: '😌' },
        { left: 'close your eyes', syllable: 'DRE', right: 'starry night', emojiLeft: '😌', emojiRight: '🌙' },
        { left: 'starry night', syllable: 'AMS', right: 'soft pillow', emojiLeft: '🌙', emojiRight: '💤' },
        { left: 'soft pillow', syllable: '', right: 'bedtime story', emojiLeft: '💤', emojiRight: '📖' },
      ],
    },
    {
      id: 'en-greetings-welcome-home',
      lang: 'en',
      pack: 'en-greetings',
      title: 'Welcome Home',
      difficulty: 'easy',
      answer: 'WELCOME HOME',
      wordLengths: [7, 4],
      startPhrase: 'open the door',
      chain: [
        { left: 'open the door', syllable: 'WEL', right: 'warm hugs', emojiLeft: '🚪', emojiRight: '🤗' },
        { left: 'warm hugs', syllable: 'COME', right: 'family dinner', emojiLeft: '🤗', emojiRight: '🍽️' },
        { left: 'family dinner', syllable: 'HO', right: 'cozy fireplace', emojiLeft: '🍽️', emojiRight: '🔥' },
        { left: 'cozy fireplace', syllable: 'ME', right: 'happy together', emojiLeft: '🔥', emojiRight: '❤️' },
        { left: 'happy together', syllable: '', right: 'open the door', emojiLeft: '❤️', emojiRight: '🚪' },
      ],
    },
  ],
};
