import type { PuzzlePack } from '../../../types/index.ts';

export const ruNames: PuzzlePack = {
  id: 'ru-names',
  title: 'Имена',
  icon: '👤',
  puzzles: [
    {
      id: 'ru-names-vitalik',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Виталик',
      answer: 'ВИТАЛИК',
      startPhrase: 'веселье и смех',
      chain: [
        { left: 'веселье и смех',    syllable: 'ВИ',  right: 'танцы до утра',      emojiLeft: '🎉', emojiRight: '💃' },
        { left: 'танцы до утра',      syllable: 'ТА',  right: 'лирическая мечта',   emojiLeft: '💃', emojiRight: '✨' },
        { left: 'лирическая мечта',   syllable: 'ЛИ',  right: 'крепкая дружба',     emojiLeft: '✨', emojiRight: '🤝' },
        { left: 'крепкая дружба',     syllable: 'К',   right: 'весёлый парень',      emojiLeft: '🤝', emojiRight: '😄' },
      ],
    },
    {
      id: 'ru-names-sashka',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Сашка',
      answer: 'САШКА',
      startPhrase: 'солнечная улыбка',
      chain: [
        { left: 'солнечная улыбка',  syllable: 'С',   right: 'активный дружок',     emojiLeft: '☀️', emojiRight: '🏃' },
        { left: 'активный дружок',   syllable: 'А',   right: 'широкая ладонь',      emojiLeft: '🏃', emojiRight: '🖐️' },
        { left: 'широкая ладонь',    syllable: 'Ш',   right: 'карие глаза',         emojiLeft: '🖐️', emojiRight: '👀' },
        { left: 'карие глаза',       syllable: 'КА',  right: 'душа компании',       emojiLeft: '👀', emojiRight: '🥳' },
      ],
    },
    {
      id: 'ru-names-zhenya',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Женя',
      answer: 'ЖЕНЯ',
      startPhrase: 'живой взгляд',
      chain: [
        { left: 'живой взгляд',           syllable: 'Ж',  right: 'естественная харизма', emojiLeft: '👁️', emojiRight: '⚡' },
        { left: 'естественная харизма',   syllable: 'Е',  right: 'настоящий друг',       emojiLeft: '⚡', emojiRight: '🫂' },
        { left: 'настоящий друг',         syllable: 'Н',  right: 'яркая личность',       emojiLeft: '🫂', emojiRight: '🌟' },
        { left: 'яркая личность',         syllable: 'Я',  right: 'добрый человек',       emojiLeft: '🌟', emojiRight: '❤️' },
      ],
    },
    {
      id: 'ru-names-dima',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Дима',
      answer: 'ДИМА',
      startPhrase: 'добрая душа',
      chain: [
        { left: 'добрая душа',      syllable: 'Д',  right: 'искренний смех',    emojiLeft: '💛', emojiRight: '😂' },
        { left: 'искренний смех',   syllable: 'И',  right: 'мягкий характер',   emojiLeft: '😂', emojiRight: '🕊️' },
        { left: 'мягкий характер',  syllable: 'М',  right: 'активная жизнь',    emojiLeft: '🕊️', emojiRight: '🚴' },
        { left: 'активная жизнь',   syllable: 'А',  right: 'надёжный человек',  emojiLeft: '🚴', emojiRight: '🛡️' },
      ],
    },
    {
      id: 'ru-names-pavel',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Павел',
      answer: 'ПАВЕЛ',
      startPhrase: 'простой парень',
      chain: [
        { left: 'простой парень',   syllable: 'П',   right: 'алый рассвет',      emojiLeft: '🙂', emojiRight: '🌅' },
        { left: 'алый рассвет',     syllable: 'А',   right: 'верный товарищ',    emojiLeft: '🌅', emojiRight: '🤜' },
        { left: 'верный товарищ',   syllable: 'ВЕ',  right: 'лёгкая походка',    emojiLeft: '🤜', emojiRight: '🚶' },
        { left: 'лёгкая походка',   syllable: 'Л',   right: 'настоящий лидер',   emojiLeft: '🚶', emojiRight: '👑' },
      ],
    },
    {
      id: 'ru-names-tanyushka',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Танюшка',
      answer: 'ТАНЮШКА',
      startPhrase: 'теплота сердца',
      chain: [
        { left: 'теплота сердца',  syllable: 'Т',   right: 'алые лепестки',   emojiLeft: '💗', emojiRight: '🌸' },
        { left: 'алые лепестки',   syllable: 'А',   right: 'нежный ветерок',  emojiLeft: '🌸', emojiRight: '🌬️' },
        { left: 'нежный ветерок',  syllable: 'Н',   right: 'южный берег',     emojiLeft: '🌬️', emojiRight: '🏖️' },
        { left: 'южный берег',     syllable: 'Ю',   right: 'шёпот волн',      emojiLeft: '🏖️', emojiRight: '🌊' },
        { left: 'шёпот волн',      syllable: 'Ш',   right: 'карий взгляд',    emojiLeft: '🌊', emojiRight: '👀' },
        { left: 'карий взгляд',    syllable: 'КА',  right: 'ласковая улыбка', emojiLeft: '👀', emojiRight: '🥰' },
      ],
    },
    {
      id: 'ru-names-elizaveta',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Елизавета',
      answer: 'ЕЛИЗАВЕТА',
      startPhrase: 'еловый лес',
      chain: [
        { left: 'еловый лес',         syllable: 'Е',    right: 'лирика души',        emojiLeft: '🌲', emojiRight: '🎶' },
        { left: 'лирика души',        syllable: 'ЛИ',   right: 'загадочный взгляд',  emojiLeft: '🎶', emojiRight: '🔮' },
        { left: 'загадочный взгляд',  syllable: 'ЗА',   right: 'вечерний сад',       emojiLeft: '🔮', emojiRight: '🌹' },
        { left: 'вечерний сад',       syllable: 'ВЕ',   right: 'тайная мечта',       emojiLeft: '🌹', emojiRight: '✨' },
        { left: 'тайная мечта',       syllable: 'ТА',   right: 'украшение вечера',   emojiLeft: '✨', emojiRight: '👑' },
      ],
    },
    {
      id: 'ru-names-anyuta',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Анюта',
      answer: 'АНЮТА',
      startPhrase: 'аромат весны',
      chain: [
        { left: 'аромат весны',     syllable: 'А',   right: 'нежный шёпот',     emojiLeft: '🌷', emojiRight: '🤫' },
        { left: 'нежный шёпот',     syllable: 'НЮ',  right: 'тихий смех',       emojiLeft: '🤫', emojiRight: '😊' },
        { left: 'тихий смех',       syllable: 'Т',   right: 'ароматный букет',  emojiLeft: '😊', emojiRight: '💐' },
        { left: 'ароматный букет',  syllable: 'А',   right: 'маленькое счастье', emojiLeft: '💐', emojiRight: '🌼' },
      ],
    },
    {
      id: 'ru-names-roman',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Роман',
      answer: 'РОМАН',
      startPhrase: 'романтичный вечер',
      chain: [
        { left: 'романтичный вечер',  syllable: 'РО',  right: 'мерцающий свет',  emojiLeft: '🌙', emojiRight: '🕯️' },
        { left: 'мерцающий свет',     syllable: 'М',   right: 'алые розы',       emojiLeft: '🕯️', emojiRight: '🌹' },
        { left: 'алые розы',          syllable: 'А',   right: 'ночная тишина',   emojiLeft: '🌹', emojiRight: '🌌' },
        { left: 'ночная тишина',      syllable: 'Н',   right: 'верный рыцарь',   emojiLeft: '🌌', emojiRight: '🛡️' },
      ],
    },
    {
      id: 'ru-names-anton',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Антон',
      answer: 'АНТОН',
      startPhrase: 'азарт победы',
      chain: [
        { left: 'азарт победы',       syllable: 'А',   right: 'напористый боец',   emojiLeft: '🏆', emojiRight: '🥊' },
        { left: 'напористый боец',    syllable: 'Н',   right: 'точный бросок',     emojiLeft: '🥊', emojiRight: '🎯' },
        { left: 'точный бросок',      syllable: 'ТО',  right: 'настойчивый дух',   emojiLeft: '🎯', emojiRight: '💪' },
        { left: 'настойчивый дух',    syllable: 'Н',   right: 'сильная воля',      emojiLeft: '💪', emojiRight: '⚡' },
      ],
    },
    {
      id: 'ru-names-viktoriya',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Виктория',
      answer: 'ВИКТОРИЯ',
      startPhrase: 'блеск победы',
      chain: [
        { left: 'блеск победы',       syllable: 'В',    right: 'искры триумфа',     emojiLeft: '🥇', emojiRight: '✨' },
        { left: 'искры триумфа',      syllable: 'И',    right: 'кубок лидера',      emojiLeft: '✨', emojiRight: '🏆' },
        { left: 'кубок лидера',       syllable: 'К',    right: 'торжество момента', emojiLeft: '🏆', emojiRight: '🎊' },
        { left: 'торжество момента',  syllable: 'ТО',   right: 'рисковая смелость', emojiLeft: '🎊', emojiRight: '🦅' },
        { left: 'рисковая смелость',  syllable: 'РИ',   right: 'яркий наряд',       emojiLeft: '🦅', emojiRight: '👗' },
        { left: 'яркий наряд',        syllable: 'Я',    right: 'звезда сцены',      emojiLeft: '👗', emojiRight: '🌟' },
      ],
    },
    {
      id: 'ru-names-kseniya',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Ксения',
      answer: 'КСЕНИЯ',
      startPhrase: 'красивый жест',
      chain: [
        { left: 'красивый жест',   syllable: 'К',   right: 'серебряный смех',  emojiLeft: '🌺', emojiRight: '🤍' },
        { left: 'серебряный смех', syllable: 'СЕ',  right: 'нежный образ',     emojiLeft: '🤍', emojiRight: '🎭' },
        { left: 'нежный образ',    syllable: 'Н',   right: 'изящный силуэт',   emojiLeft: '🎭', emojiRight: '💃' },
        { left: 'изящный силуэт',  syllable: 'И',   right: 'яркая натура',     emojiLeft: '💃', emojiRight: '🌟' },
        { left: 'яркая натура',    syllable: 'Я',   right: 'тонкий вкус',      emojiLeft: '🌟', emojiRight: '💎' },
      ],
    },
    {
      id: 'ru-names-irina',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Ирина',
      answer: 'ИРИНА',
      startPhrase: 'искренняя улыбка',
      chain: [
        { left: 'искренняя улыбка',  syllable: 'И',  right: 'радостный день',   emojiLeft: '😍', emojiRight: '☀️' },
        { left: 'радостный день',    syllable: 'Р',  right: 'игривый смех',     emojiLeft: '☀️', emojiRight: '😄' },
        { left: 'игривый смех',      syllable: 'И',  right: 'нежное слово',     emojiLeft: '😄', emojiRight: '🤍' },
        { left: 'нежное слово',      syllable: 'Н',  right: 'алый закат',       emojiLeft: '🤍', emojiRight: '🌅' },
        { left: 'алый закат',        syllable: 'А',  right: 'тихая гавань',     emojiLeft: '🌅', emojiRight: '⚓' },
      ],
    },
    {
      id: 'ru-names-andrey',
      lang: 'ru',
      pack: 'ru-names',
      title: 'Андрей',
      answer: 'АНДРЕЙ',
      startPhrase: 'ароматное утро',
      chain: [
        { left: 'ароматное утро',      syllable: 'А',    right: 'напористый характер', emojiLeft: '☕', emojiRight: '🔥' },
        { left: 'напористый характер', syllable: 'Н',    right: 'дружеский смех',      emojiLeft: '🔥', emojiRight: '😄' },
        { left: 'дружеский смех',      syllable: 'Д',    right: 'рейтинг лучших',      emojiLeft: '😄', emojiRight: '🏅' },
        { left: 'рейтинг лучших',      syllable: 'РЕЙ',  right: 'надёжная рука',       emojiLeft: '🏅', emojiRight: '🤝' },
      ],
    },
  ],
};
